require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LocImagesController do

  # This should return the minimal set of attributes required to create a valid
  # LocImage. As you add validations to LocImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "image_location" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all loc_images as @loc_images" do
      loc_image = LocImage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:loc_images).should eq([loc_image])
    end
  end

  describe "GET show" do
    it "assigns the requested loc_image as @loc_image" do
      loc_image = LocImage.create! valid_attributes
      get :show, {:id => loc_image.to_param}, valid_session
      assigns(:loc_image).should eq(loc_image)
    end
  end

  describe "GET new" do
    it "assigns a new loc_image as @loc_image" do
      get :new, {}, valid_session
      assigns(:loc_image).should be_a_new(LocImage)
    end
  end

  describe "GET edit" do
    it "assigns the requested loc_image as @loc_image" do
      loc_image = LocImage.create! valid_attributes
      get :edit, {:id => loc_image.to_param}, valid_session
      assigns(:loc_image).should eq(loc_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LocImage" do
        expect {
          post :create, {:loc_image => valid_attributes}, valid_session
        }.to change(LocImage, :count).by(1)
      end

      it "assigns a newly created loc_image as @loc_image" do
        post :create, {:loc_image => valid_attributes}, valid_session
        assigns(:loc_image).should be_a(LocImage)
        assigns(:loc_image).should be_persisted
      end

      it "redirects to the created loc_image" do
        post :create, {:loc_image => valid_attributes}, valid_session
        response.should redirect_to(LocImage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved loc_image as @loc_image" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocImage.any_instance.stub(:save).and_return(false)
        post :create, {:loc_image => { "image_location" => "invalid value" }}, valid_session
        assigns(:loc_image).should be_a_new(LocImage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocImage.any_instance.stub(:save).and_return(false)
        post :create, {:loc_image => { "image_location" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested loc_image" do
        loc_image = LocImage.create! valid_attributes
        # Assuming there are no other loc_images in the database, this
        # specifies that the LocImage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LocImage.any_instance.should_receive(:update).with({ "image_location" => "MyString" })
        put :update, {:id => loc_image.to_param, :loc_image => { "image_location" => "MyString" }}, valid_session
      end

      it "assigns the requested loc_image as @loc_image" do
        loc_image = LocImage.create! valid_attributes
        put :update, {:id => loc_image.to_param, :loc_image => valid_attributes}, valid_session
        assigns(:loc_image).should eq(loc_image)
      end

      it "redirects to the loc_image" do
        loc_image = LocImage.create! valid_attributes
        put :update, {:id => loc_image.to_param, :loc_image => valid_attributes}, valid_session
        response.should redirect_to(loc_image)
      end
    end

    describe "with invalid params" do
      it "assigns the loc_image as @loc_image" do
        loc_image = LocImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => loc_image.to_param, :loc_image => { "image_location" => "invalid value" }}, valid_session
        assigns(:loc_image).should eq(loc_image)
      end

      it "re-renders the 'edit' template" do
        loc_image = LocImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => loc_image.to_param, :loc_image => { "image_location" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested loc_image" do
      loc_image = LocImage.create! valid_attributes
      expect {
        delete :destroy, {:id => loc_image.to_param}, valid_session
      }.to change(LocImage, :count).by(-1)
    end

    it "redirects to the loc_images list" do
      loc_image = LocImage.create! valid_attributes
      delete :destroy, {:id => loc_image.to_param}, valid_session
      response.should redirect_to(loc_images_url)
    end
  end

end
